package me.whereareiam.anvil.api.scenario;

import me.whereareiam.anvil.api.model.scenario.AnvilScenario;
import org.jetbrains.annotations.NotNull;

/**
 * Defines one complete Anvil scenario for direct, type-safe selection.
 *
 * <p>A definition owns the complete environment used by a test. Its scenario may contain one
 * server or a network of proxies and servers. Build integrations expose definition classes from
 * the compiled project through {@value #INDEX_RESOURCE}; tooling loads those classes only after
 * the project runtime has been prepared. JUnit can select a definition class directly.</p>
 *
 * <pre>{@code
 * public final class RegistrationScenario implements AnvilScenarioDefinition {
 *     @Override
 *     public AnvilScenario define() {
 *         return AnvilScenario.builder()
 *                 .name("registration")
 *                 .server(registrationServer())
 *                 .entrypoint("registration")
 *                 .build();
 *     }
 * }
 * }</pre>
 */
public interface AnvilScenarioDefinition {
	/**
	 * Resource containing one fully qualified definition class name per line.
	 *
	 * <p>The resource is generated by a build integration after compilation. Empty lines and lines
	 * beginning with {@code #} are ignored. The resource deliberately contains classes rather than
	 * evaluated scenarios so that metadata and topology remain owned by the definition itself.</p>
	 */
	String INDEX_RESOURCE = "META-INF/anvil/scenarios";

	/**
	 * Creates the scenario to run.
	 *
	 * @return complete scenario definition
	 */
	@NotNull AnvilScenario define();
}
