package me.whereareiam.anvil.platform.neoforge;

import me.whereareiam.anvil.api.model.process.MinecraftServer;
import me.whereareiam.anvil.platform.api.exception.PlatformException;
import me.whereareiam.anvil.platform.api.model.PlatformContext;
import me.whereareiam.anvil.platform.api.type.ForwardingMode;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Applies NeoForge listener settings to the existing server properties and writes the EULA answer.
 */
final class NeoForgeConfiguration {
	void write(MinecraftServer server, PlatformContext context) throws IOException {
		if (context.getForwarding().getMode() != ForwardingMode.NONE)
			throw new PlatformException("NeoForge does not support identity forwarding");

		writeProperties(server, context);
		Files.writeString(context.getWorkDirectory().resolve("eula.txt"),
				"eula=" + context.isEulaAccepted() + "\n", StandardCharsets.UTF_8);
	}

	private void writeProperties(MinecraftServer server, PlatformContext context) throws IOException {
		Path file = context.getWorkDirectory().resolve("server.properties");
		Properties properties = new Properties();
		if (Files.exists(file))
			try (var reader = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
				properties.load(reader);
			}

		server.getSettings().forEach(properties::setProperty);
		properties.setProperty("server-ip", context.getBindAddress());
		properties.setProperty("server-port", Integer.toString(context.getPort()));
		properties.setProperty("online-mode", Boolean.toString(server.isOnlineMode()));
		properties.setProperty("motd", "Anvil: " + server.getName());
		properties.setProperty("spawn-protection", "0");
		properties.setProperty("enable-rcon", "false");

		try (var writer = Files.newBufferedWriter(file, StandardCharsets.UTF_8)) {
			properties.store(writer, "Generated by Anvil");
		}
	}
}
