package me.whereareiam.anvil.platform.paper;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import me.whereareiam.anvil.api.model.process.MinecraftServer;
import me.whereareiam.anvil.platform.api.exception.PlatformException;
import me.whereareiam.anvil.platform.api.model.PlatformContext;
import me.whereareiam.anvil.platform.api.type.ForwardingMode;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Applies Paper runtime settings to existing properties and YAML documents.
 */
final class PaperConfiguration {
	private final YAMLMapper yaml = YAMLMapper.builder()
			.enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION)
			.disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER).build();

	void write(MinecraftServer server, PlatformContext context) throws IOException {
		writeProperties(server, context);
		Files.writeString(context.getWorkDirectory().resolve("eula.txt"),
				"eula=" + context.isEulaAccepted() + "\n", StandardCharsets.UTF_8);
		writeForwarding(context);
	}

	private void writeProperties(MinecraftServer server, PlatformContext context) throws IOException {
		Path file = context.getWorkDirectory().resolve("server.properties");
		Properties properties = new Properties();
		if (Files.exists(file))
			try (var reader = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
				properties.load(reader);
			}
		server.getSettings().forEach(properties::setProperty);
		properties.setProperty("server-ip", context.getBindAddress());
		properties.setProperty("server-port", Integer.toString(context.getPort()));
		properties.setProperty("online-mode", Boolean.toString(server.isOnlineMode()));
		properties.setProperty("motd", "Anvil: " + server.getName());
		properties.setProperty("spawn-protection", "0");
		properties.setProperty("enable-rcon", "false");
		try (var writer = Files.newBufferedWriter(file, StandardCharsets.UTF_8)) {
			properties.store(writer, "Generated by Anvil");
		}
	}

	private void writeForwarding(PlatformContext context) throws IOException {
		var forwarding = context.getForwarding();
		boolean modern = forwarding.getMode() == ForwardingMode.MODERN;
		Path paperFile = context.getWorkDirectory().resolve("config/paper-global.yml");
		ObjectNode paper = read(paperFile);
		ObjectNode velocity = paper.withObject("/proxies/velocity");
		velocity.put("enabled", modern);
		velocity.put("online-mode", forwarding.isProxyOnlineMode());
		velocity.remove("secret");
		if (modern) {
			if (forwarding.getSecret() == null)
				throw new PlatformException("Modern forwarding requires a negotiated secret");
			velocity.put("secret", forwarding.getSecret());
		}
		Files.createDirectories(paperFile.getParent());
		yaml.writeValue(paperFile.toFile(), paper);

		Path spigotFile = context.getWorkDirectory().resolve("spigot.yml");
		ObjectNode spigot = read(spigotFile);
		spigot.withObject("/settings").put("bungeecord", forwarding.getMode() == ForwardingMode.LEGACY);
		yaml.writeValue(spigotFile.toFile(), spigot);
	}

	private ObjectNode read(Path file) throws IOException {
		if (!Files.exists(file))
			return yaml.createObjectNode();
		JsonNode document = yaml.readTree(file.toFile());
		if (document == null)
			return yaml.createObjectNode();
		if (document instanceof ObjectNode object)
			return object;
		throw new PlatformException("Paper configuration must contain a YAML mapping: " + file);
	}
}
