package me.whereareiam.anvil.platform.spigot;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import me.whereareiam.anvil.api.model.process.MinecraftServer;
import me.whereareiam.anvil.platform.api.exception.PlatformException;
import me.whereareiam.anvil.platform.api.model.PlatformContext;
import me.whereareiam.anvil.platform.api.type.ForwardingMode;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Applies Spigot listener settings and updates forwarding in the existing YAML document.
 */
final class SpigotConfiguration {
	private final YAMLMapper yaml = YAMLMapper.builder()
			.enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION)
			.disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER).build();

	void write(MinecraftServer server, PlatformContext context) throws IOException {
		if (context.getForwarding().getMode() == ForwardingMode.MODERN)
			throw new PlatformException("Spigot does not support modern forwarding");

		writeProperties(server, context);
		Files.writeString(context.getWorkDirectory().resolve("eula.txt"),
				"eula=" + context.isEulaAccepted() + "\n", StandardCharsets.UTF_8);
		Path file = context.getWorkDirectory().resolve("spigot.yml");
		ObjectNode document = read(file);
		document.withObject("/settings").put("bungeecord", context.getForwarding().getMode() == ForwardingMode.LEGACY);
		yaml.writeValue(file.toFile(), document);
	}

	private void writeProperties(MinecraftServer server, PlatformContext context) throws IOException {
		Path file = context.getWorkDirectory().resolve("server.properties");
		Properties properties = new Properties();
		if (Files.exists(file))
			try (var reader = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
				properties.load(reader);
			}

		server.getSettings().forEach(properties::setProperty);
		properties.setProperty("server-ip", context.getBindAddress());
		properties.setProperty("server-port", Integer.toString(context.getPort()));
		properties.setProperty("online-mode", Boolean.toString(server.isOnlineMode()));
		properties.setProperty("motd", "Anvil: " + server.getName());
		properties.setProperty("spawn-protection", "0");

		try (var writer = Files.newBufferedWriter(file, StandardCharsets.UTF_8)) {
			properties.store(writer, "Generated by Anvil");
		}
	}

	private ObjectNode read(Path file) throws IOException {
		if (!Files.exists(file)) return yaml.createObjectNode();
		JsonNode document = yaml.readTree(file.toFile());
		if (document == null) return yaml.createObjectNode();
		if (document instanceof ObjectNode object) return object;

		throw new PlatformException("Spigot configuration must contain a YAML mapping: " + file);
	}
}
