plugins {
	java
}

// What loads a shipped JAR reads the module version from it: plugin descriptors declare it as ${version}, and
// the manifest's Implementation-Version backs Package.getImplementationVersion(). Velocity's descriptor is
// generated by its annotation processor into the classes, so it is expanded while packaging instead. The version
// is read lazily, after the build files have set it, and the actions capture only that provider.
val moduleVersion = provider { project.version.toString() }

tasks.named<ProcessResources>("processResources") {
	val descriptorVersion = moduleVersion
	inputs.property("descriptorVersion", descriptorVersion)
	filesMatching(listOf("plugin.yml", "bungee.yml", "META-INF/anvil/plugin.properties")) {
		expand("version" to descriptorVersion.get())
	}
}

// Every JAR task, so a shaded JAR carries the attribute whether or not it inherits the plain JAR's manifest.
tasks.withType<Jar>().configureEach {
	val descriptorVersion = moduleVersion
	inputs.property("descriptorVersion", descriptorVersion)
	doFirst {
		manifest.attributes["Implementation-Version"] = descriptorVersion.get()
	}
	filesMatching("velocity-plugin.json") {
		expand("version" to descriptorVersion.get())
	}
}
